# ? Realiza el build y push de la iamgen utilizando el dockerfile.prod
steps:
  - name: "gcr.io/cloud-builders/docker"
    args: 
      [
        "build",
        "-t",
        "northamerica-south1-docker.pkg.dev/store-microservices-459102/image-registry/products-microservice",
        "-f",
        "dockerfile.prod",
        "--platform=linux/amd64",
        "."
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      [
        "push",
        "northamerica-south1-docker.pkg.dev/store-microservices-459102/image-registry/products-microservice",
      ]
options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
